name: Qodana Code Quality

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  qodana-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@v2026.1
        with:
          args: --linter,jetbrains/qodana-jvm-community